version: "3.8"
services:
  db:
    image: postgres:17
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:ABA@Acleda168@db:5432/attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ABA@Acleda168
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
